version: '3.8'

services:
  postgres15:
    image: postgres:15
    container_name: postgres15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres15_data:/var/lib/postgresql/data

volumes:
  postgres15_data:
